spring:
  application:
    name: redis-in-spring
  profiles:
    default: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2/db/redis-in-spring
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org.springframework.cache: trace